### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by pwalsh**
**DO NOT MERGE: WORK IN PROGRESS**

This pull request is for discussion as I port over parts I need while using datapackage.

The first thing that needs agreement, is that I am not intending to use `six`. `six` is great, especially for porting over large projects (e.g.: Django), but here, we have a small, focussed codebase, that is quite manageable without it. I've been working recently on similar small codebases for Py2.7/3.3+ support, and  find the following working well:

* Using a compat.py file (several high profile Python libraries use this, e.g., [Requests](https://github.com/kennethreitz/requests))
* Following the official [porting guide](https://docs.python.org/3/howto/pyporting.html)

For examples, see [Good Tables](https://github.com/okfn/goodtables) and [JTSKit](https://github.com/okfn/jtskit-py), which I'm currently working on with this approach.

So, I'm raising this now to ensure that this approach is legit here, before I get too far into the port.

### CODE REVIEW

**Comment by tryggvib** [comment]
Yes I think this would be an improvement over the amount of "RY" (repeat yourselves) we have. Agreed!

**Comment by pwalsh** [comment]
Hey @tryggvib 

Things are looking good: I've gone over everything and now have one failing test on Py2.7, and 2 failing tests (includes the one fail on 2.x) on Python 3.4.

It would be great if we could run this against travis with several runtimes.

### The common fail

This one is weird because the assert is correct when I go interactive with a debugger...

```
======================================================================
FAIL: test_resource.TestDatapackage.test_guess_format
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/paulwalsh/code/environments/datapackage/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/paulwalsh/code/projects/datapackage/tests/test_resource.py", line 250, in test_guess_format
    assert self.resource._guess_format() == 'jpeg'
AssertionError
```

### The Py3.x fail

This is because [here](https://github.com/pwalsh/datapackage/blob/feature/py3/datapackage/schema.py#L135), `type(reference_fields)` is `<class 'str'>` (in the py3 sense), and `value_type` is `<class 'datapackage.schema.Field'>`. I didn't try to see why.

```
======================================================================
ERROR: test_resource.TestDatapackage.test_resource_schema_foreign_key_Field_field
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/paulwalsh/code/environments/datapackage/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/paulwalsh/code/projects/datapackage/tests/test_resource.py", line 600, in test_resource_schema_foreign_key_Field_field
    fields=villain, reference=villains)
  File "/Users/paulwalsh/code/projects/datapackage/datapackage/util.py", line 51, in __init__
    self.__setattr__(key, value)
  File "/Users/paulwalsh/code/projects/datapackage/datapackage/schema.py", line 137, in __setattr__
    'Fields must have the same type as Reference fields')
TypeError: Fields must have the same type as Reference fields
```

**Comment by tryggvib** [comment]
Added Travis integration (badge coming up) but we're getting quite a few errors (for Python 2 they're because of the pep8 tests I added although I have not been able to reproduce on them on my machine)

**Comment by pwalsh** [comment]
Had a quick look at the output of travis: the pep8 is checking is really strict (and probably doesn't apply to Py3 changes directly). It might be good to disable that for a little while, until we can get the Py3-specific changes verified?

**Comment by tryggvib** [comment]
Yes that's what I'm looking at now.

**Comment by tryggvib** [comment]
Flake8 temporarily removed from development branch (Travis running)

**Comment by pwalsh** [comment]
@tryggvib should this pull request be against develop?

**Comment by tryggvib** [comment]
@pwalsh Doesn't matter. I would like to keep master branch as clean as possible and the dev branch was thought of as something for bigger changes people would like to collaborate on. You can achieve the same thing in your own fork.

**Comment by pwalsh** [comment]
Hey @tryggvib about that first error I mentioned above, see this in master:

https://github.com/tryggvib/datapackage/blob/master/tests/test_resource.py#L249

I see I changed 'jpe' to 'jpeg' [ref](https://github.com/pwalsh/datapackage/blob/feature/py3/tests/test_resource.py#L250) as I thought it was a typo/

**Comment by pwalsh** [comment]
Hey @tryggvib about the Py3 only bug, not sure why it is not raising on Py2, but this is what is happening:

at this point: https://github.com/pwalsh/datapackage/blob/master/tests/test_resource.py#L598

we get into here: https://github.com/pwalsh/datapackage/blob/master/datapackage/schema.py#L90

inside __setattr__, at this line: https://github.com/pwalsh/datapackage/blob/master/datapackage/schema.py#L104

we have:

```
ipdb> attribute, value, value_type
('fields', {'name': 'villain', 'title': 'Movie villain'}, <class 'datapackage.schema.Field'>)
```

But here, value is changed from an instance of a Field to the name of the field: https://github.com/pwalsh/datapackage/blob/master/datapackage/schema.py#L125

So this test fails:

https://github.com/pwalsh/datapackage/blob/master/datapackage/schema.py#L134

I have no idea why I only see this on Py3 and not on Py2: it seems clear there is a bug in the code unrelated to runtime, unless I am missing something.

Now that I've identified what is leading to the two errors above, would you be able to take a look and tell me what you think/help fix them?

**Comment by pwalsh** [comment]
The 'jpe' to 'jpeg' failing test is caused by a bug in Python. See http://bugs.python.org/issue4963.

In order to provide consistency across Python runtimes and os hosts, I've made the following change (ref. https://github.com/tryggvib/datapackage/commit/d7fd8f2eba9afcff385ebed4cf7c274709a0c906) which ensures that any guess from mime types, that returns a jpeg extension, is normalized to a canonical form: `jpg`. I chose `jpg` over the other forms as other tests in the code check for that version of the JPEG extension.

**Comment by pwalsh** [comment]
Ok, so now, the status is:

* tests pass consistently on Py2.6, Py2.7, Py3.2
* The Py3 failing test mentioned here: https://github.com/tryggvib/datapackage/pull/33#issuecomment-86500073 is actually only failing on Python 3.3 and Python 3.4, and it is not consistent. I'm running Py3.4 locally, and the failing is random: I can trigger test suite after test suite, and around 50% of the time that test fails, and otherwise passes. I have not successfully tracked down the bug. Any help would be great.
* Failing status on travis is from the flake8 check, not the tests.

**Comment by tryggvib** [comment]
I'm wondering if we shouldn't just merge this into master, in hopes that others might be able to help narrow down the bug. I'll start by merging it into development.

**Pull request merged**
